title: Alfredo Emiliano Chavez Pantiga
logo: /assets/img/yo_curriculum.jpg
description: Physical engineer who likes computers, programming and data science
#show_downloads: true
theme: jekyll-theme-minimal
